language: ruby
rvm:
  - 2.2
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --assume-extension --only-4xx --check-favicon --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
