- name: "Sturdy Templates"
  icon: fa fa-4x fa-diamond
  description: "Our templates are updated regularly so they don't break."
  delay: .0s
- name: "Ready to Ship"
  icon: fa fa-4x fa-paper-plane
  description: "You can use this theme as is, or you can make changes!"
  delay: .1s
- name: "Up to Date"
  icon: fa fa-4x fa-newspaper-o
  description: "We update dependencies to keep things fresh."
  delay: .2s
- name: "Made with Love"
  icon: fa fa-4x fa-heart
  description: "You have to make your websites with love these days!"
  delay: .3s
